### ISSUE TITLE
Fail when install sql server and db connection

### ISSUE THREAD

**Issue by DucQuynh02** [Anh26535D/NMCNPM.20221-Nhom10#31]
- Guide to install sql server with full-text search
- Edit add_data_fee sql file
- TCP/IP error 1433

**Comment by Anh26535D** [comment]
TCP/IP error 1433:
- Open SQL Server Configuration Manager
- Navigate SQL Server Network Configuration / Protocol for ...
- Right click to TCP/IP, select enable
- Double click TCP/IP, navigate IP Addresses > IPAll > Port. Fill 1433, then Apply
